In [4]:
import pandas as pd
import numpy as np
from sklearn.decomposition import NMF

In [5]:
# Sample non-negative matrix
V = np.array([[1, 0, 0, 1, 0, 0],
              [0, 1, 0, 1, 1, 0],
              [0, 0, 1, 1, 0, 1]
              ])
print("Orignal Matrix V: \n", V)

Orignal Matrix V: 
 [[1 0 0 1 0 0]
 [0 1 0 1 1 0]
 [0 0 1 1 0 1]]


In [7]:
# We set n_components to 2, meaning we want to find a factorization with a rank of 2.
# We create an NMF object. 
# The init='random' parameter tells the algorithm to initialize W and H with random non-negative values. 
# Random_state=0 is used for reproducibility.

n_components = 2
model = NMF(n_components=n_components, init='random', random_state=42)
W = model.fit_transform(V)
H = model.components_

print("\nMatrix W (Document-Component matrix):\n", W)
print("\nMatrix H (Component-Term matrix):\n", H)

V_constructed = np.dot(W, H)
print('Reconstructed V Matrix: \n', V_constructed)


Matrix W (Document-Component matrix):
 [[0.00000000e+00 1.01271248e+00]
 [1.39363280e+00 2.19581252e-04]
 [1.39410467e+00 0.00000000e+00]]

Matrix H (Component-Term matrix):
 [[0.00000000e+00 3.58653097e-01 3.58774543e-01 7.17349885e-01
  3.58653097e-01 3.58774543e-01]
 [9.87447056e-01 1.07087784e-04 0.00000000e+00 9.87447115e-01
  1.07087784e-04 0.00000000e+00]]
Reconstructed V Matrix: 
 [[9.99999953e-01 1.08449135e-04 0.00000000e+00 1.00000001e+00
  1.08449135e-04 0.00000000e+00]
 [2.16824861e-04 4.99830743e-01 4.99999971e-01 9.99939154e-01
  4.99830743e-01 4.99999971e-01]
 [0.00000000e+00 4.99999957e-01 5.00169266e-01 1.00006082e+00
  4.99999957e-01 5.00169266e-01]]


In [ ]:
def simple_doc_processor(doc_list, words_to_remove):
    '''
    
    '''
    processed_docs = [] #empty list
    for doc in doc_list:
        words = doc.split(" ") # get words
        words = [word.lower() for word in words] # lowercase
        words = [word for word in words if word not in words_to_remove] #membership tes
        processed_docs.append(words)

    vocab = [j for i in processed_docs for j in i]
    unique_vocab = list(set(vocab))

    doc_vocabindex_list = []




    return processed_docs    
