In [4]:
import pandas as pd
import numpy as np
from sklearn.decomposition import NMF

In [5]:
# Sample non-negative matrix
V = np.array([[1, 0, 0, 1, 0, 0],
              [0, 1, 0, 1, 1, 0],
              [0, 0, 1, 1, 0, 1]
              ])
print("Orignal Matrix V: \n", V)

Orignal Matrix V: 
 [[1 0 0 1 0 0]
 [0 1 0 1 1 0]
 [0 0 1 1 0 1]]


In [7]:
# We set n_components to 2, meaning we want to find a factorization with a rank of 2.
# We create an NMF object. 
# The init='random' parameter tells the algorithm to initialize W and H with random non-negative values. 
# Random_state=0 is used for reproducibility.

n_components = 2
model = NMF(n_components=n_components, init='random', random_state=42)
W = model.fit_transform(V)
H = model.components_

print("\nMatrix W (Document-Component matrix):\n", W)
print("\nMatrix H (Component-Term matrix):\n", H)

V_constructed = np.dot(W, H)
print('Reconstructed V Matrix: \n', V_constructed)


Matrix W (Document-Component matrix):
 [[0.00000000e+00 1.01271248e+00]
 [1.39363280e+00 2.19581252e-04]
 [1.39410467e+00 0.00000000e+00]]

Matrix H (Component-Term matrix):
 [[0.00000000e+00 3.58653097e-01 3.58774543e-01 7.17349885e-01
  3.58653097e-01 3.58774543e-01]
 [9.87447056e-01 1.07087784e-04 0.00000000e+00 9.87447115e-01
  1.07087784e-04 0.00000000e+00]]
Reconstructed V Matrix: 
 [[9.99999953e-01 1.08449135e-04 0.00000000e+00 1.00000001e+00
  1.08449135e-04 0.00000000e+00]
 [2.16824861e-04 4.99830743e-01 4.99999971e-01 9.99939154e-01
  4.99830743e-01 4.99999971e-01]
 [0.00000000e+00 4.99999957e-01 5.00169266e-01 1.00006082e+00
  4.99999957e-01 5.00169266e-01]]


In [ ]:
np.random.random((4, 5)) # so a random intializaed matrix of shape 4 * 5
 

array([[0.38171419, 0.95867122, 0.36545576, 0.92864867, 0.18530055],
       [0.53946039, 0.74051724, 0.23183566, 0.78153311, 0.50958433],
       [0.0971198 , 0.33266287, 0.30153062, 0.54594536, 0.90045422],
       [0.42065857, 0.14569788, 0.61972919, 0.59936271, 0.0145109 ]])